### ISSUE TITLE
Saving included file does not process variables from other included files

### ISSUE THREAD

**Issue by jkclose** [armin-pfaeffle/sass-autocompile#113]
I am getting an undefined variable error when saving an included file.

Here is an example of what I am referring to:

main.scss
_variables.scss
_mobile.scss

A variable referenced in _mobile that is defined in _variables will be undefined.

**Comment by armin-pfaeffle** [comment]
Can you post a minimal example please?

**Comment by jkclose** [comment]
Sorry, I don't have a set of files I can easily upload. I'll expand on the idea I started in the original post.

With this file structure:
main.scss
_variables.scss
_mobile.scss

**main.scss:**
// Sass variables
@import "partials/variables";

// Mobile Styles
@import "partials/mobile";


**_variables.scss:**
$text-color: #5c6b80;

**_mobile.scss**
p {
  color: $text-color;
}

If I save **main.scss** everything is fine, if I save **_variables.scss** everything is fine, but if I save **_mobile.scss**, it gives an error that $text-color is undefined. It appears that the processing is unable to look at other included files for variable definition?

Thanks for taking time to look at this.

**Comment by armin-pfaeffle** [comment]
Ahhh, now I know where the problem comes from! When saving `_mobile.scss`, it does not know anything about `_variables.scss`, because there is no import command; only `_mobile.scss` is compiled and there is no `$text-color` definition.

The solution: you should add a first-line-comment to `_mobile.scss` and `_variables.scss`, so when saving these files, `main.scss` is compiled!

Content of `_mobile.scss`:
```scss
// main: ../main.scss

p {
    color: $text-color;
}
```

Content of `_variables.scss`:
```scss
// main: ../main.scss

$text-color: #5c6b80;
```

Now, everything should work as expected!

**Comment by jkclose** [comment]
That works. Thanks!

I saw references to the first line comments, but must have missed exactly how they work.

**Comment by armin-pfaeffle** [comment]
I think, I should improve the documentation a lil bit...
