### ISSUE TITLE
Sass build error Node Sass doe snot support current environment.

### ISSUE THREAD

**Issue by iamshipon1988** [armin-pfaeffle/sass-autocompile#155]
Upgraded Node and NPM and after I started receiving this error when compiling.

> /usr/local/lib/node_modules/node-sass/lib/binding.js:13
>       throw new Error(errors.unsupportedEnvironment());
>       ^
> 
> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v4.5.3
>     at module.exports (/usr/local/lib/node_modules/node-sass/lib/binding.js:13:13)
>     at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/bin/node-sass:11:10)

I tried the old fix which was to run  `npm rebuild node-sass`  but it did not fix it in this case. Any fix for this issue?

**Comment by armin-pfaeffle** [comment]
Hey!

Which version of node and npm is installed on your Macs? Please execute `node --version` and `npm --version` in your terminal and post the versions.

Have you installed 64-bit version of node?

**Comment by iamshipon1988** [comment]
node 10.6.0
npm 6.1.0
And yes 64-bit

**Comment by armin-pfaeffle** [comment]
Hm... Okay... On my windows, node 10.7.0, npm 6.1.0, node-sass 4.9.2 is working without problems. I have to try in my VM.

**Comment by armin-pfaeffle** [comment]
Which version of node-sass do you use? Terminal -> `node-sass --version`

Have you tried removing and re-installing node-sass?

**Comment by armin-pfaeffle** [comment]
I've installed macOS High Sierre (10.13.6) in my VM, node 10.7.0, npm 6.1.0, node-sass 4.9.2, Atom 1.28.2 and everything works.

**Comment by iamshipon1988** [comment]
I was on Mac. I initially thought it was node/npm/node-sass, so I removed all and reinstalled but still same issue.

Node-sass is 4.9.2

**Comment by armin-pfaeffle** [comment]
Which macOS version do you use? It's a lil' bit like searching a needle in a haystack, because macOS is not the OS I am using.

Beside that I had a look at the executables:
```
Sepps-Mac:~ sepp$ file /usr/local/bin/node
/usr/local/bin/node: Mach-O 64-bit executable x86_64

Sepps-Mac:~ sepp$ file /usr/local/bin/npm
/usr/local/bin/npm: a /usr/bin/env node script text executable, UTF-8 Unicode text

Sepps-Mac:~ sepp$ file /Users/sepp/.npm-global/bin/node-sass
/Users/sepp/.npm-global/bin/node-sass: a /usr/bin/env node script text executable, ASCII text
```

Does this correspond to your output?

**Comment by iamshipon1988** [comment]
Hey Armin,

Very sorry for the late response. I found out that while updating node there was an error that occurred. Removing node through terminal, for whatever reason, ended up not removing the node folder within brew. After removing it manually, and reinstalling node through brew, fixed the problem. Works like a charm. 

Next question, will you be adding the ability to auto-generate css.map file?

Big fan of this plugin. 💌

**Comment by armin-pfaeffle** [comment]
Thanks for posting your solution! Perhaps it helps others. 

> Next question, will you be adding the ability to auto-generate css.map file?

No ;) Because this functionality is already there. You can enable in it globally by setting the [corresponding option](https://github.com/armin-pfaeffle/sass-autocompile#build-source-map) in the package settings or  enable it for each file/project by extending the first line comment with [sourceMap parameters](https://github.com/armin-pfaeffle/sass-autocompile#sourcemap):

```sass
// compileCompressed: ../$1.min.css, compileNested: ../$1.css, sourceMap: true
```

**Comment by nimmolo** [comment]
For others who may have this problem ( I just spent 8 hours on this, uninstalling node & npm & nvm, reinstalling many many times ) :

Armin has very helpfully put a field in settings to point to the executable file for node-sass, **wherever** it may have been installed. 

Check Atom settings for sass-autocompile. (Preferences - Packages - Sass Autocompile)

Check that "Path to 'node-sass' command" is set to the right location. In my case the mystery was that npm was installing global packages in /usr/local/bin but they were not able to run due to permissions. Rather than change the permissions on this folder i [changed the directory where npm installs global packages](https://stackoverflow.com/questions/33725639/npm-install-g-less-does-not-work) and reinstalled node-sass globally .
